#cloud-config

users:
  - name: yc-user
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - MY_PUBLIC_SSH_KEY

# Update apt database on first boot (run 'apt-get update').
package_update: true

# Install additional packages on first boot
packages:
 - git

# run commands
runcmd:
 - [ git, clone, --branch, cloud-testapp, 'https://github.com/Otus-DevOps-2022-05/klimenko-sergey_infra.git' ]
 - [ sh, ./klimenko-sergey_infra/install_ruby.sh ]
 - [ sh, ./klimenko-sergey_infra/install_mongodb.sh ]
 - [ sh, ./klimenko-sergey_infra/deploy.sh ]
