---
# tasks file for app
- name: apt update
  ansible.builtin.apt:
    update_cache: yes
- name: Wait for sudo
  become: yes
  shell:  while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

- name: Install git
  ansible.builtin.apt:
    name: git
    state: present

# - name: Add unit file for Puma
#   copy:
#     src: puma.service
#     dest: /etc/systemd/system/puma.service
#   notify: reload puma

# - name: Add config for DB connection
#   template:
#     src: db_config.j2
#     dest: /home/ubuntu/db_config
#     owner: ubuntu
#     group: ubuntu

# - name: enable puma
#   systemd: name=puma enabled=yes

- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment!!!"

# - include_tasks: nginx.yml
- include_tasks: ruby.yml
- include_tasks: puma.yml
